# Generated by Django 5.0.3 on 2024-05-27 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên tòa nhà")),
                ("address", models.CharField(max_length=255, verbose_name="Địa chỉ")),
                (
                    "number_of_floors",
                    models.PositiveSmallIntegerField(verbose_name="Số lượng tầng"),
                ),
            ],
            options={
                "verbose_name": "Tòa nhà",
                "verbose_name_plural": "Các tòa nhà",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.PositiveSmallIntegerField(verbose_name="Tầng")),
                ("room_code", models.CharField(max_length=20, verbose_name="Mã phòng")),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Sức chứa"
                    ),
                ),
                (
                    "is_lock",
                    models.BooleanField(default=False, verbose_name="Khóa phòng"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.building",
                        verbose_name="Tòa nhà",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phòng",
                "verbose_name_plural": "Các phòng",
                "unique_together": {("building", "room_code")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Họ và tên"),
                ),
                (
                    "gender",
                    models.TextField(
                        choices=[("Nam", "Male"), ("Nữ", "Female"), ("Khác", "Other")],
                        default="Nam",
                        max_length=4,
                        verbose_name="Giới tính",
                    ),
                ),
                ("platoon", models.CharField(max_length=50, verbose_name="Trung đội")),
                ("squad", models.CharField(max_length=50, verbose_name="Tiểu đội")),
                ("position", models.CharField(max_length=50, verbose_name="Chức vụ")),
                (
                    "headmaster",
                    models.CharField(max_length=50, verbose_name="Chủ nhiệm Trung Đội"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.room",
                        verbose_name="Phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Học viên",
                "verbose_name_plural": "Các học viên",
            },
        ),
    ]
