# Generated by Django 5.0.3 on 2025-04-07 12:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên tòa nhà")),
                (
                    "number_of_floors",
                    models.PositiveSmallIntegerField(verbose_name="Số lượng tầng"),
                ),
                (
                    "number_of_room_each_floor",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Số lượng phòng mỗi tầng"
                    ),
                ),
                (
                    "capacity_each_room",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Số lượng học viên mỗi phòng"
                    ),
                ),
                (
                    "female_priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        verbose_name="Độ ưu tiên (dành cho xếp ưu tiên kí túc xá nữ)",
                    ),
                ),
                (
                    "male_priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        verbose_name="Độ ưu tiên (dành cho xếp ưu tiên kí túc xá nam)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tòa nhà",
                "verbose_name_plural": "Tòa nhà",
            },
        ),
        migrations.CreateModel(
            name="Platoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên Trung đội"),
                ),
            ],
            options={
                "verbose_name": "Trung đội",
                "verbose_name_plural": "Trung đội",
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor_number", models.PositiveSmallIntegerField(verbose_name="Tầng")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="backend.building",
                        verbose_name="Tòa nhà",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Student", "Học viên"),
                            ("Headmaster", "Chủ nhiệm trung đội"),
                            ("Admin", "Quản lý phần mềm"),
                            ("Room Manager", "Lãnh đạo phòng"),
                        ],
                        default="Học viên",
                        max_length=256,
                        verbose_name="Vai trò",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_groups",
                        to="auth.group",
                        verbose_name="Nhóm",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_permissions",
                        to="auth.permission",
                        verbose_name="Quyền người dùng",
                    ),
                ),
                (
                    "buildings",
                    models.ManyToManyField(
                        blank=True,
                        to="backend.building",
                        verbose_name="Các tòa nhà quản lý",
                    ),
                ),
                (
                    "floors",
                    models.ManyToManyField(
                        blank=True, to="backend.floor", verbose_name="Các tầng quản lý"
                    ),
                ),
                (
                    "platoon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.platoon",
                        verbose_name="Trung đội",
                    ),
                ),
            ],
            options={
                "verbose_name": "Người dùng",
                "verbose_name_plural": "Người dùng",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.CharField(max_length=20, verbose_name="Mã phòng")),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Sức chứa"
                    ),
                ),
                (
                    "is_lock",
                    models.BooleanField(
                        default=False, verbose_name="Khóa phòng cố định"
                    ),
                ),
                (
                    "is_temporary_lock",
                    models.BooleanField(
                        default=False, verbose_name="Khóa phòng tạm thời"
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.building",
                        verbose_name="Tòa nhà",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.floor",
                        verbose_name="Tầng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phòng",
                "verbose_name_plural": "Phòng",
                "unique_together": {("building", "room_code")},
            },
        ),
        migrations.AddField(
            model_name="floor",
            name="rooms",
            field=models.ManyToManyField(
                blank=True,
                related_name="floors",
                to="backend.room",
                verbose_name="Phòng",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Họ và tên"),
                ),
                (
                    "gender",
                    models.TextField(
                        choices=[("Nam", "Male"), ("Nữ", "Female"), ("Khác", "Other")],
                        default="Nữ",
                        max_length=4,
                        verbose_name="Giới tính",
                    ),
                ),
                ("squad", models.CharField(max_length=50, verbose_name="Tiểu đội")),
                (
                    "position",
                    models.CharField(max_length=50, null=True, verbose_name="Chức vụ"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "headmaster",
                    models.CharField(max_length=50, verbose_name="Chủ nhiệm Trung Đội"),
                ),
                (
                    "platoon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.platoon",
                        verbose_name="Trung đội",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.room",
                        verbose_name="Phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Học viên",
                "verbose_name_plural": "Học viên",
            },
        ),
        migrations.AlterUniqueTogether(
            name="floor",
            unique_together={("building", "floor_number")},
        ),
    ]
