# Generated by Django 5.0.3 on 2024-06-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="number_of_room_each_floor",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Số lượng phòng mỗi tầng"
            ),
        ),
    ]
