# Generated by Django 5.0.3 on 2025-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_lock_to_move",
            field=models.BooleanField(
                default=False, verbose_name="Khóa học sinh bị dời ra ngoài "
            ),
        ),
    ]
