# Generated by Django 5.0.3 on 2024-06-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_building_number_of_room_each_floor"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Độ ưu tiên"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.TextField(
                choices=[("Nam", "Male"), ("Nữ", "Female"), ("Khác", "Other")],
                default="Nữ",
                max_length=4,
                verbose_name="Giới tính",
            ),
        ),
    ]
